const _=global
//ignoreAllByLibal
//libalCodingHelper
//Sheba
//labDepartment

/**
 * Direct pdfmake Hebrew Test - Skip HTML conversion
 * Use pdfmake directly with Hebrew text
 */

async function main(context) {
    const { ColorLog, pdfMake, moment, fsExtra } = context;
    
    ColorLog.BW('🚀 Direct pdfmake Hebrew Test');
    ColorLog.BW('=============================');
    
    try {
        if (!pdfMake) {
            ColorLog.RW('❌ pdfMake not available');
            return { success: false, error: 'pdfMake not available' };
        }
        
        ColorLog.GW('✅ pdfMake available');
        
        // Create document definition with Hebrew text
        const docDefinition = {
            info: {
                title: 'Hebrew PDF Test',
                author: 'RunCodeV3',
                subject: 'Direct Hebrew Text Test'
            },
            content: [
                {
                    text: 'Hebrew PDF Test - בדיקת PDF בעברית',
                    style: 'header',
                    alignment: 'right'
                },
                {
                    text: '========================',
                    alignment: 'center',
                    margin: [0, 0, 0, 20]
                },
                {
                    text: 'שלום עולם - זהו מבחן ליצירת PDF בעברית',
                    alignment: 'right',
                    margin: [0, 0, 0, 10]
                },
                {
                    text: `תאריך: ${moment().format('DD/MM/YYYY')}`,
                    alignment: 'right',
                    margin: [0, 0, 0, 10]
                },
                {
                    text: `שעה: ${moment().format('HH:mm:ss')}`,
                    alignment: 'right',
                    margin: [0, 0, 0, 10]
                },
                {
                    text: 'אותיות עבריות: אבגדהוזחטיכלמנסעפצקרשת',
                    alignment: 'right',
                    margin: [0, 0, 0, 10]
                },
                {
                    text: 'מספרים: 1234567890',
                    alignment: 'right',
                    margin: [0, 0, 0, 10]
                },
                {
                    text: 'English + עברית mixed text',
                    alignment: 'left',
                    margin: [0, 0, 0, 10]
                },
                {
                    text: [
                        'Platform: ',
                        { text: process.platform, bold: true },
                        '\nNode Version: ',
                        { text: process.version, bold: true },
                        '\nGenerated by: RunCodeV3'
                    ],
                    margin: [0, 20, 0, 0]
                }
            ],
            styles: {
                header: {
                    fontSize: 18,
                    bold: true
                }
            },
            defaultStyle: {
                fontSize: 12,
                lineHeight: 1.3
            }
        };
        
        ColorLog.BW('📄 Creating PDF with pdfmake...');
        
        // Generate filename
        const filename = `direct_hebrew_${moment().format('YYYYMMDD_HHmmss')}.pdf`;
        
        try {
            // Initialize pdfmake with fonts
            const PdfPrinter = pdfMake;
            const printer = new PdfPrinter({
                Roboto: {
                    normal: 'Helvetica',
                    bold: 'Helvetica-Bold',
                    italics: 'Helvetica-Oblique',
                    bolditalics: 'Helvetica-BoldOblique'
                }
            });
            
            // Create PDF document
            const pdfDoc = printer.createPdfKitDocument(docDefinition);
            
            // Get buffer from PDFKit document
            const chunks = [];
            pdfDoc.on('data', chunks.push.bind(chunks));
            const buffer = await new Promise((resolve, reject) => {
                pdfDoc.on('end', () => {
                    resolve(Buffer.concat(chunks));
                });
                pdfDoc.on('error', reject);
                pdfDoc.end();
            });
            
            // Save to file
            await fsExtra.writeFile(filename, buffer);
            
            // Check file stats
            const stats = await fsExtra.stat(filename);
            
            ColorLog.GW(`✅ Direct Hebrew PDF generated: ${filename}`);
            ColorLog.GW(`📊 Size: ${stats.size} bytes`);
            ColorLog.YB('📋 Check PDF to see if Hebrew displays correctly with right alignment');
            
            return {
                success: true,
                filename: filename,
                size: stats.size,
                method: 'Direct pdfmake with Hebrew'
            };
            
        } catch (pdfError) {
            ColorLog.RW('❌ PDF generation error:', pdfError.message);
            throw pdfError;
        }
        
    } catch (error) {
        ColorLog.RW('❌ Direct pdfmake test failed:', error.message);
        return { success: false, error: error.message };
    }
}